baseurl: "" # 网站子路径, e.g. /blog
url: "https://three-ant.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site_name: "三只蚂蚁"

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

paginate: 10
paginate_path: "/posts/page/:num"


# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages


# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed