baseURL = "http://localhost:1313/"
languageCode = "zh-CN"
title = "三只蚂蚁"
theme = "hugo-threeant"


[params]
  site_name= "三只蚂蚁"
  paginate = 2
  email = "contact@threeant.cn"
  qq = "123456789"
  dingtak = ""


[content]
  posts = "content/posts"
[permalinks]
  posts = "/posts/:slug/"
[taxonomies]
  category = "categories"
  tag = "tags"
